### ISSUE TITLE
Mario jitters back and forth when beside/inside a fence.

### ISSUE THREAD

**Issue by ayunami2000** [Retro64Mod/Retro64Mod#14] opened 2022-03-21 20:13 UTC
![GIF 3-21-2022 4-11-13 PM](https://user-images.githubusercontent.com/24785136/159355786-c0dd30d6-b615-41f1-856d-3da7cd4fc19a.gif)

gif framerate is low, in reality its much faster. sorry!

this happens when mario jumps towards a fence. he will get stuck inside of it (he can escape by jumping out of it)

**Comment by dylanpdx** [comment] 2022-03-26 00:14
Duplicate of https://github.com/Retro64Mod/Retro64Mod.github.io/issues/21

**Closed by dylanpdx** 2022-03-26 00:14 UTC
